version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: playlistApi
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
    networks:
      - my-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-api-container
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=playlistApi;User=user;Password=pass;
    depends_on:
      - mysql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
